### ISSUE TITLE
Disable Post-Effect on demand

### ISSUE THREAD

**Issue by fefo-dev** [kkots/ggxrd_freecam#2] opened 2024-12-01 16:26 UTC
Might be obvious, but can you toogle post-effects within your tool? That would enable easy screenshoting without manually setting everything up. Even in the likeness of a reload being necessary it would be easier for those who use the effect.

Unrelated to it but I'm very happy to see an active developer working on this game. Maybe you could add a frame meter to it in the future 🙂

**Comment by kkots** [comment] 2024-12-02 00:56
This is incredible, but I managed to very quickly find a solution for this that works without having to reload the current match! I'm going to get to making an update right away. Thank you for suggesting this!
A framebar is in an early stage of the works and will be coming in a near future. But it's not ready yet, so in the next update I will only include the Post Effects toggle.
I will write a new comment when that is done.

**Comment by kkots** [comment] 2024-12-02 07:24
@fefo-dev Alright I published a release that contains this feature: https://github.com/kkots/ggxrd_freecam/releases/tag/2.7
It has two new settings in the INI file:
1) turnOffPostEffectWhenMakingBackgroundBlack - is set to true by default. This makes it so that when you press the blackBackgroundToggle, Post-Effect automatically gets turned off, and when you press it again, it gets turned back on.
2) togglePostEffectsOnOff - a keyboard shortcut, which is not set by default. This allows you to manually control the Post-Effect setting, if you want.

Both options allow Post-Effect to be changed without reloading a match!

Please let me know if everything works fine, so I can make any changes still needed and close this issue.

**Comment by fefo-dev** [comment] 2024-12-02 10:04
Thanks a lot, I'll check it later and report back.

> A framebar is in an early stage of the works

👀👀👀👀👀👀

**Comment by fefo-dev** [comment] 2024-12-02 16:58
Just checked - working as intended, although I couldn't swap/add any keybindings. A bit confusing since I didn't notice that even without effects the pictures aren't fully opaque, but after testing on the previous version it became clear.

Seems that the .ini file alterations are ignored as of now, be it after the injection or on a cold boot. Mind checking it?

I can create another issue if you want, as I want to get my controller working for this.

**Comment by kkots** [comment] 2024-12-02 20:08
> Just checked - working as intended, although I couldn't swap/add any keybindings.

Depending on what language you use, some keys might not work properly on it. For example, in Japanese IME, even English mode, the button "1" may stop working if you pressed and released it when in Japanese IME, Hiragana mode.
It is best to use the keyboard shortcuts with the plain English language.

> even without effects the pictures aren't fully opaque

Attempting to take screenshots with transparency when the background is not black, even if Post-Effect is turned off, will result in screenshots that have partially transparent parts, like the tension bars. To take screenshots without transparency either use the regular print screen button on the keyboard, or set dontUseScreenshotTransparency = true in the INI.

> Seems that the .ini file alterations are ignored as of now, be it after the injection or on a cold boot. Mind checking it?

The INI file changes are taken into account for me in real time. Were you changing the INI file that is in the game's Binaries/Win32 directory, where GuiltyGearXrd.exe file is? That's where the mod is looking for the INI file. Changing the INI file that is next to the ggxrd_freecam_injector.exe won't achieve anything, because after the mod is loaded it doesn't even remember where the injector was that you used to inject it with.

> I can create another issue if you want, as I want to get my controller working for this.

The controller support in the mod is both easy and difficult to implement. It's easy if I just being some new solution to the table that the game doesn't already have, like a library or code made by someone else that handles controllers. It's difficult if I try to use the controller support that the game already has and attempt to somehow obtain inputs from that. The latter is more preferable because it brings fewer new dependencies into the mod but it much more difficult.
If you want the controller to work you can make a new issue and I'll see if this is suddenly easy and some breakthrough happens like with Post-Effect.

@fefo-dev Please confirm where the INI file you tried changing was and about key bindings situation, as these appear to be quite important problems.

**Comment by fefo-dev** [comment] 2024-12-02 20:46
I downloaded, extracted and ran the injector (didn't try the patcher). No file was moved from that folder.

> .ini rebinding

I kept rebindings within Fkeys, for example setting F5 to pause. After saving the file the game still used F3 to pause, even after unloading/reloading the .dll or relaunching the game. Just now I tried to change the HUD toogle to F4, but it's still on F1.

> transparency

Here's an example - game started, dll hooked, F2 then F8 after adjusting camera
![example](https://files.catbox.moe/yuyds4.png)

While this image looks opaque, there's a small amount of transparency in each section. You can see the transparency pattern bleeding through if you zoom in:
![alpha](https://files.catbox.moe/gs0sn3.png)

No issue IMO, but I thought you should know. Each color has a consistent alpha value, which makes me think it has to do with shading or something.

> controller

I have other mods slightly similar to yours so I thought you had the support already, or it was easy to change. No worries.

**Comment by fefo-dev** [comment] 2024-12-02 20:54
Haven't thought about it, but if you paste the image on Paint it _kinda_ doesn't happen... because Paint does not support alpha.

The save in folder function is working and I could compare both the saved image and the one I sent: both are similar if you throw a white background on mine. A small technicality if anything.

**Comment by kkots** [comment] 2024-12-02 21:51
> .ini rebinding

This really bugs me. There was an issue I just discovered and fixed, with allowNextFrameKey actually being named allowNextFrame inside the mod. I released version 2.7.2 for this. But the other hotkeys work fine for me. Are you sure you're changing the INI in the game's Binaries/Win32? The freeze game toggle should be named freezeGameToggle, and hide hud toggle toggleHud. Last ditch effort: can you send me the INI file, so I can try it for myself? Maybe the file is encoded in UTF16 instead of UTF8?

> transparency

Yes! I managed to reproduce this issue. I could add a checkbox setting that would make it so that any non-0 alpha pixel becomes 255 alpha. This needs to be done without changing the colors. Putting a white background underneath the image, like you did, would make the colors slightly brighter. Let me know if you need that checkbox. It will make semi-transparent effects like 5D warning flash also fully opaque, so maybe that's not a very good solution. This problem overall is kind of terrifying.

> controller

OK, no controller for now. Maybe later.

**Comment by fefo-dev** [comment] 2024-12-02 23:06
> Are you sure you're changing the INI in the game's Binaries/Win32?

No, I was changing [ggxrd_freecam.ini](https://files.catbox.moe/hjhxly.ini) in my download folder. It didn't create any ini file there, or anywhere else (there was some files from your hitbox overlay but I deleted them to make sure).

The image doesn't bother me and is hardly noticeable, with easy fixes as you said. I wouldn't mind. If anything I prefer the "bugged" effect ones, you can be fancy with them:

![](https://files.catbox.moe/vhbncr.png)

**Comment by kkots** [comment] 2024-12-02 23:34
Alright then, we can finally close this issue! The problem was that, in order for your INI file changes to take any effect, they must be placed inside the same folder where the game's GuiltyGearXrd.exe executable is. For example, I have the game installed on D:\SteamLibrary\common\GUILTY GEAR Xrd -REVELATOR-\, so I have to place the ggxrd_freecam.ini file in here:
D:\SteamLibrary\steamapps\common\GUILTY GEAR Xrd -REVELATOR-\Binaries\Win32
You might have the game installed at C:\Program Files (x86)\Steam\steamapps\common\GUILTY GEAR Xrd -REVELATOR-\ and would need to place the INI file in <that folder>\Binaries\Win32.

Thank you for your participation in this project, and I'll be looking forward to more issues in the future, haha!

**Closed as completed by kkots** 2024-12-02 23:34 UTC
